config/routes.rb
Minicms::Application.routes.draw do
  resources :documents

  resources :images

  resources :events

  resources :sponsors

  resources :users

  resources :sites

  resources :menus

end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :entity_type %><br />
    <%= f.text_field :entity_type %>
  </div>
  <div class="field">
    <%= f.label :entity_id %><br />
    <%= f.number_field :entity_id %>
  </div>
  <div class="field">
    <%= f.label :upload_file_name %><br />
    <%= f.text_field :upload_file_name %>
  </div>
  <div class="field">
    <%= f.label :upload_content_type %><br />
    <%= f.text_field :upload_content_type %>
  </div>
  <div class="field">
    <%= f.label :upload_file_size %><br />
    <%= f.number_field :upload_file_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Entity type</th>
    <th>Entity</th>
    <th>Upload file name</th>
    <th>Upload content type</th>
    <th>Upload file size</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.name %></td>
    <td><%= document.entity_type %></td>
    <td><%= document.entity_id %></td>
    <td><%= document.upload_file_name %></td>
    <td><%= document.upload_content_type %></td>
    <td><%= document.upload_file_size %></td>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Entity type:</b>
  <%= @document.entity_type %>
</p>

<p>
  <b>Entity:</b>
  <%= @document.entity_id %>
</p>

<p>
  <b>Upload file name:</b>
  <%= @document.upload_file_name %>
</p>

<p>
  <b>Upload content type:</b>
  <%= @document.upload_content_type %>
</p>

<p>
  <b>Upload file size:</b>
  <%= @document.upload_file_size %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>